function [fitresult, gof] = safeFit(SoC_cut, voltage_cut)
%CREATEFIT(SOC_CUT,VOLTAGE_CUT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: SoC_cut
%      Y Output: voltage_cut
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Nov-2024 10:46:00


%% Fit
[xData, yData] = prepareCurveData( SoC_cut, voltage_cut );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'voltage_cut vs. SoC_cut', 'Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'SoC_cut', 'Interpreter', 'none' );
ylabel( 'voltage_cut', 'Interpreter', 'none' );
xlim([0 1])
ylim([2 4.5])
box on
grid on


